sudo: false
language: python
cache: pip
python:
  - "2.7"
  - "3.5"
  - "3.6"
install: pip install -r requirements.txt
script: scripts/ci
after_success:
  - pip install -q codecov scrutinizer-ocular
  - codecov
  - ocular --data-file ".coverage" --config-file ".coveragerc"
notifications:
  email: false